# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a2c3b8175ce22ff2ea42a6694a31cfe4aa6e0c8408e46857313b59850c36fda6f864b874530a198d06a1ed0ce9b4e66832aca55de9a53c64f54d0a53735abc3

test:
  secret_key_base: 855248c569bb6b45987895d693af0d02d0fcc616321111b6fc7eb795cb34947df62f752b0b5d1dbbe9e673ef28d77c9e961174413a44cb6a264f129555ea32ce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
